import type { Metadata,Suspense } from "next";
import { Inter } from "next/font/google";
import Navbar from "../components/navigation/Navbar";
import { Suspense } from "react";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="flex flex-row w-screen bg-zinc-950">
          <Navbar />
          {children}
        </div>
      </body>
    </html>
  );
}
