import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Navbar from "../components/navigation/Navbar";
import { Suspense } from "react";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="flex flex-row">
          <div className="flex flex-col">
            <div className="bg-zinc-950">
              <div className="h-14 p-2 flex flex-row justify-end items-center">
                <img src="/F1-logo-white.png" className=" mr-8 h-6" />
              </div>
              {children}
            </div>
          </div>
        </div>
      </body>
    </html>
  );
}
